### ISSUE TITLE
documentation links in navbar open in same tab

### ISSUE THREAD

**Issue by KaiWaldrant** [openproblems-bio/website#149]
when quarto 1.3 releases add `target: _blank` in navbar option for documentation in the `_quarto.yaml` file. If documentation for v2 is not finished. see quarto-dev/quarto-cli#2284

```yaml
menu:
  - text: OpenProblems v1
    href: https://github.com/openproblems-bio/openproblems/blob/main/CONTRIBUTING.md
  - text: OpenProblems v2
    href: https://github.com/openproblems-bio/openproblems-v2/blob/main/CONTRIBUTING.md
```

```yaml
menu:
  - text: OpenProblems v1
    href: https://github.com/openproblems-bio/openproblems/blob/main/CONTRIBUTING.md
    target: _blank
  - text: OpenProblems v2
    href: https://github.com/openproblems-bio/openproblems-v2/blob/main/CONTRIBUTING.md
    target: _blank
```
