### ISSUE TITLE
[v2 docs] document `directives`

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/website#218]
Nowhere on the Contribute -> Add a method page does it explain to me how to select directives. If I want to use a GPU for my method, how do I do it?

**Comment by rcannood** [comment]
Good point. The notation would be:

```yaml
platforms:
  - type: docker
    ...
  - type: nextflow
    directives: 
      label: [ midcpu, midmem, gpu ]
```

I'll look into where to store this information.
